// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZDy5UZm3E-L5lCQzCzf3tn7eVwlK3cU',
    appId: '1:139367019165:web:a01f07d344e2ae6ab65a74',
    messagingSenderId: '139367019165',
    projectId: 'quizapp-flutter-fireship',
    authDomain: 'quizapp-flutter-fireship.firebaseapp.com',
    storageBucket: 'quizapp-flutter-fireship.appspot.com',
    measurementId: 'G-2E7KF2VL7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuM6bDCcUKN6Ydm1oP3AjC-7Sl5IDJKKM',
    appId: '1:139367019165:android:a41615ecf3ec0a84b65a74',
    messagingSenderId: '139367019165',
    projectId: 'quizapp-flutter-fireship',
    storageBucket: 'quizapp-flutter-fireship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUCdbOv_2fh-WctRA_zpvpgTkBrVmYAI',
    appId: '1:139367019165:ios:1d5a8b4a21619933b65a74',
    messagingSenderId: '139367019165',
    projectId: 'quizapp-flutter-fireship',
    storageBucket: 'quizapp-flutter-fireship.appspot.com',
    iosClientId: '139367019165-79f5nm87oodol8ds4kv5upamanlmhira.apps.googleusercontent.com',
    iosBundleId: 'net.neeoon.quizapp',
  );
}
